services:
  - type: web
    name: libreria-ia-backend
    env: node
    plan: free # El plan gratuito es ideal para empezar
    buildCommand: "npm install"
    startCommand: "node server.js"
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: "20.11.0" # Versión LTS recomendada
      - key: GOOGLE_AI_API_KEY
        sync: false # Sincronización desactivada para que la gestiones desde el dashboard de Render
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false 