# Generated by Django 5.2.3 on 2025-06-10 14:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('description', models.TextField(verbose_name='Descripción detallada')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('quality_category', models.CharField(choices=[('economico', 'Económico'), ('intermedio', 'Intermedio'), ('calidad', 'Calidad')], max_length=20, verbose_name='Categoría de calidad')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL de la imagen')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la lista')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Lista de Compras',
                'verbose_name_plural': 'Listas de Compras',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name_raw', models.CharField(max_length=300, verbose_name='Nombre del artículo (texto original)')),
                ('quantity_requested', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad solicitada')),
                ('ai_suggestions_json', models.JSONField(blank=True, null=True, verbose_name='Sugerencias de IA en formato JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistente_compras.shoppinglist', verbose_name='Lista de compras')),
                ('suggested_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asistente_compras.product', verbose_name='Producto sugerido por la IA')),
            ],
            options={
                'verbose_name': 'Ítem de Lista de Compras',
                'verbose_name_plural': 'Ítems de Lista de Compras',
                'ordering': ['created_at'],
            },
        ),
    ]
