# Generated by Django 5.2.3 on 2025-06-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistente_compras', '0002_alter_shoppinglist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='quality_preference',
            field=models.CharField(choices=[('cualquiera', 'Cualquier calidad'), ('economico', 'Solo económicos'), ('intermedio', 'Solo intermedios'), ('calidad', 'Solo de calidad')], default='cualquiera', max_length=20, verbose_name='Preferencia de calidad'),
        ),
    ]
